# 服务端口
server:
  port: 8201

# 服务名
spring:
  application:
    name: service-hosp

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appt_reg?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: LZYXXF0928@pyx

  # 返回json的全局时间格式
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    # 开启sentinel
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858

  # mongodb地址
  data:
    mongodb:
      host: 192.168.10.100
      port: 27017
      database: appt_reg_hosp

  # rabbitmq地址
  rabbitmq:
    host: 192.168.10.100
    port: 5672
    username: panyx
    password: panyx

# 配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  level:
    root: debug

