server:
  port: 9100 # 服务端口

spring:
  application:
    name: service-gateway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # 使用服务发现路由
      routes:
        - id: service-hosp # 设置路由id
          uri: lb://service-hosp # 设置路由的uri
          predicates: Path=/*/hosp/** # 设置路由断言,代理servicerId为auth-service的/auth/路径
        - id: service-cmn # 设置路由id
          uri: lb://service-cmn # 设置路由的uri
          predicates: Path=/*/cmn/** # 设置路由断言,代理servicerId为auth-service的/auth/路径
        - id: service-user # 设置路由id
          uri: lb://service-user # 设置路由的uri
          predicates: Path=/*/user/** # 设置路由断言,代理servicerId为auth-service的/auth/路径
        - id: service-msm # 设置路由id
          uri: lb://service-msm # 设置路由的uri
          predicates: Path=/*/msm/** # 设置路由断言,代理servicerId为auth-service的/auth/路径
        - id: service-user # 设置路由id
          uri: lb://service-user # 设置路由的uri
          predicates: Path=/*/ucenter/** # 设置路由断言,代理servicerId为auth-service的/auth/路径
        - id: service-oss # 设置路由id
          uri: lb://service-oss # 设置路由的uri
          predicates: Path=/*/oss/** # 设置路由断言,代理servicerId为auth-service的/auth/路径
        - id: service-order # 设置路由id
          uri: lb://service-order # 设置路由的uri
          predicates: Path=/*/order/** # 设置路由断言,代理servicerId为auth-service的/auth/路径