server:
  port: 8206
spring:
  application:
    name: service-order
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.44.165:3306/appt_reg?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: LZYXXF0928@pyx
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://192.168.10.100:27017/appt_reg_hosp
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 192.168.10.100
    port: 5672
    username: panyx
    password: panyx

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲


# 配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

weixin:
  pay:
    # 关联的公众号appid
    appid: xxxxxxxxxxxxxxxxxx
    # 商户号
    partner: xxxxxxxxxxxxxxxxx
    # 商户key
    partnerkey: xxxxxxxxxxxxxxxxxxxxxx
    #退款证书
    cert: D:\\IDEAPriceProject\\Graduation-Design\\APPT_REG\\API\\APPT_REG_API\\service\\service-order\\src\\main\\resources\\cert\\apiclient_cert.p12